rem ______________________________________________________________ replace encoding mode as utf-8 _________________________________________________________________
chcp 65001



rem ______________________________________________________________ translation _________________________________________________________________
start chrome -new-window "https://www.google.com/search?q=eng+to+kor&sxsrf=ALiCzsapsT0ZsQvhVg0MWwFJDRhs2jyAVg%3A1652320993883&ei=4Wp8YrPHNYz1sAfxo7uQBg&ved=0ahUKEwjzu5Sv79j3AhWMOuwKHfHRDmIQ4dUDCA4&uact=5&oq=eng+to+kor&gs_lcp=Cgdnd3Mtd2l6EAMyBwgjELADECcyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAELADEENKBAhBGABKBAhGGABQAFgAYJQBaAFwAXgAgAEAiAEAkgEAmAEAyAEKwAEB&sclient=gws-wiz"
start chrome "https://www.google.com/search?q=kor+to+eng&sxsrf=ALiCzsaAzycTn-tARg2XLSNXzoy-k0bRPQ%3A1652322067084&ei=E298YtzNBMbSkwWP9JjABQ&ved=0ahUKEwico_Ou89j3AhVG6aQKHQ86BlgQ4dUDCA4&uact=5&oq=kor+to+eng&gs_lcp=Cgdnd3Mtd2l6EAMyBwgjELADECcyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyBwgAEEcQsAMyEgguEMcBENEDEMgDELADEEMYATISCC4QxwEQ0QMQyAMQsAMQQxgBSgQIQRgASgQIRhgAUABYAGCmAmgBcAF4AIABAIgBAJIBAJgBAMgBC8ABAdoBBAgBGAg&sclient=gws-wiz"
