rem __________________________ replace encoding mode as utf-8_________________________ 
chcp 65001


REM // ______________________________________________________________ categories _________________________________________________________________
explorer "C:\Users\human\desktop\alpha\categories"